# Generated by Django 6.0.4 on 2026-05-04 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_attack', models.IntegerField(default=0, verbose_name='Очки атакой (ОЗ)')),
                ('points_block', models.IntegerField(default=0, verbose_name='Очки блоком (ОБ)')),
                ('points_serve', models.IntegerField(default=0, verbose_name='Очки подачей (ОП)')),
                ('aces', models.IntegerField(default=0, verbose_name='Эйсы')),
                ('blocks', models.IntegerField(default=0, verbose_name='Блоки')),
                ('errors', models.IntegerField(default=0, verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Статистика игрока за матч',
                'verbose_name_plural': 'Статистика игроков за матчи',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Запланирован'), ('LIVE', 'Идёт'), ('FINISHED', 'Завершён'), ('CANCELLED', 'Отменён')], default='SCHEDULED', max_length=20, verbose_name='Статус')),
                ('score_home', models.IntegerField(blank=True, null=True, verbose_name='Счёт хозяев')),
                ('score_away', models.IntegerField(blank=True, null=True, verbose_name='Счёт гостей')),
                ('protocol_file', models.FileField(blank=True, null=True, upload_to='protocols/%Y/%m/', verbose_name='Протокол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.championship', verbose_name='Чемпионат')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date_time'],
            },
        ),
    ]
