# Generated by Django 6.0.4 on 2026-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchset'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
    ]
