# Generated by Django 6.0.4 on 2026-05-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mvp_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_away_matches', to=settings.AUTH_USER_MODEL, verbose_name='MVP гостей'),
        ),
        migrations.AddField(
            model_name='match',
            name='mvp_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_home_matches', to=settings.AUTH_USER_MODEL, verbose_name='MVP хозяев'),
        ),
        migrations.AddField(
            model_name='match',
            name='protocol_photo',
            field=models.ImageField(blank=True, null=True, upload_to='protocols/photos/', verbose_name='Фото протокола'),
        ),
        migrations.AddField(
            model_name='match',
            name='stream_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на трансляцию'),
        ),
        migrations.AddField(
            model_name='match',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на запись'),
        ),
        migrations.CreateModel(
            name='MatchReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=None, null=True, verbose_name='Принял назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='matches.match', verbose_name='Матч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
            ],
            options={
                'verbose_name': 'Судья матча',
                'verbose_name_plural': 'Судьи матчей',
                'unique_together': {('match', 'user')},
            },
        ),
    ]
