# Generated by Django 6.0.5 on 2026-05-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_fields_and_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchstats',
            name='aces',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='errors',
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='passes',
            field=models.IntegerField(default=0, verbose_name='Передачи (П)'),
        ),
    ]
