# Generated by Django 6.0.4 on 2026-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(verbose_name='Игровой номер')),
                ('position', models.CharField(choices=[('SETTER', 'Связующий'), ('OUTSIDE_HITTER', 'Доигровщик'), ('OPPOSITE', 'Диагональный'), ('LIBERO', 'Либеро'), ('MIDDLE_BLOCKER', 'Центральный блокирующий')], max_length=20, verbose_name='Амплуа')),
            ],
            options={
                'verbose_name': 'Игрок команды',
                'verbose_name_plural': 'Игроки команд',
                'ordering': ['jersey_number'],
            },
        ),
    ]
