# Generated by Django 6.0.5 on 2026-05-07 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teaminvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.AddField(
            model_name='team',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_teams', to=settings.AUTH_USER_MODEL, verbose_name='Основатель'),
        ),
    ]
