# Generated by Django 6.0.5 on 2026-05-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_created_by_team_founder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamplayer',
            options={'ordering': ['-is_main', 'jersey_number'], 'verbose_name': 'Игрок команды', 'verbose_name_plural': 'Игроки команд'},
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Основной состав'),
        ),
    ]
