# Generated by Django 6.0.5 on 2026-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_teamplayer_options_teamplayer_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Основной состав'),
        ),
    ]
