# Generated by Django 6.0.4 on 2026-05-06 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('matches', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решена')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='StatisticianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
            ],
            options={
                'verbose_name': 'Назначение статиста',
                'verbose_name_plural': 'Назначения статистов',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_link',
            field=models.URLField(blank=True, verbose_name='Макс'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_channel',
            field=models.URLField(blank=True, verbose_name='Telegram-канал'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_link',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_link',
            field=models.URLField(blank=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MODERATOR', 'Модератор'), ('REFEREE', 'Судья'), ('STATISTICIAN', 'Статист'), ('PLAYER', 'Игрок')], default='PLAYER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'middle_name', 'birth_date'), name='unique_person'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Нарушитель'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='statisticianassignment',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statisticians', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='statisticianassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistician_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Статист'),
        ),
        migrations.AlterUniqueTogether(
            name='statisticianassignment',
            unique_together={('user', 'match')},
        ),
    ]
