# Generated by Django 6.0.5 on 2026-05-07 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_championship_league_type'),
        ('users', '0002_report_statisticianassignment_user_city_user_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(default='🏅', max_length=10, verbose_name='Иконка')),
                ('color', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('bronze', 'Бронза'), ('diamond', 'Бриллиант')], default='gold', max_length=20, verbose_name='Уровень')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='leagues.championship', verbose_name='Чемпионат')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Награда турнира',
                'verbose_name_plural': 'Награды турниров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдана')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.award', verbose_name='Награда')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_awards', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Награда игрока',
                'verbose_name_plural': 'Награды игроков',
                'unique_together': {('player', 'award')},
            },
        ),
    ]
