# Generated by Django 6.0.5 on 2026-05-07 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_award_playeraward'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(max_length=50, verbose_name='Тип награды')),
                ('level', models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('diamond', 'Бриллиант')], default='bronze', max_length=20, verbose_name='Уровень')),
                ('value', models.IntegerField(default=0, verbose_name='Значение (очки/матчи/разы)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_awards', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Автонаграда',
                'verbose_name_plural': 'Автонаграды',
                'unique_together': {('player', 'award_type')},
            },
        ),
    ]
