# Generated by Django 6.0.5 on 2026-05-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_siteaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaward',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
    ]
