# Generated by Django 6.0.4 on 2026-05-04 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название чемпионата')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое название')),
                ('league_type', models.CharField(choices=[('CLASSIC', 'Классический волейбол'), ('BEACH', 'Пляжный волейбол')], max_length=10, verbose_name='Тип волейбола')),
                ('description', models.TextField(verbose_name='Описание')),
                ('about_founders', models.TextField(blank=True, verbose_name='Об основателях')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk_link', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('max_link', models.URLField(blank=True, verbose_name='Макс')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='championships/logos/', verbose_name='Логотип')),
                ('primary_color', models.CharField(default='#1a73e8', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Вторичный цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Чемпионат',
                'verbose_name_plural': 'Чемпионаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='championships/photos/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='leagues.championship', verbose_name='Чемпионат')),
            ],
            options={
                'verbose_name': 'Фотография чемпионата',
                'verbose_name_plural': 'Фотографии чемпионатов',
                'ordering': ['order'],
            },
        ),
    ]
