# Generated by Django 6.0.4 on 2026-05-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='league_type',
            field=models.CharField(choices=[('CLASSIC', 'Классический волейбол'), ('BEACH', 'Пляжный волейбол'), ('PARK', 'Парковый волейбол')], max_length=10, verbose_name='Тип волейбола'),
        ),
    ]
