# Generated by Django 6.0.5 on 2026-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_championship_league_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('recruiting', 'Идёт набор команд'), ('finished', 'Завершён')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
