# Generated by Django 6.0.5 on 2026-05-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_championship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founders/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='leagues.championship', verbose_name='Чемпионат')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
                'ordering': ['order'],
            },
        ),
    ]
