# Generated by Django 6.0.5 on 2026-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
