# Generated by Django 6.0.5 on 2026-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_championship_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Короткое название'),
        ),
    ]
