# Generated by Django 6.0.5 on 2026-05-08 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_championship_short_name'),
        ('teams', '0007_teaminvite_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='applications_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн заявок'),
        ),
        migrations.AddField(
            model_name='championship',
            name='regulations',
            field=models.TextField(blank=True, verbose_name='Положение'),
        ),
        migrations.AddField(
            model_name='championship',
            name='stage',
            field=models.CharField(choices=[('applications', 'Сбор заявок'), ('review', 'Приём заявок окончен'), ('active', 'Идёт'), ('finished', 'Завершён')], default='applications', max_length=20, verbose_name='Этап'),
        ),
        migrations.CreateModel(
            name='ChampionshipTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрена')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Подана')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='leagues.championship', verbose_name='Чемпионат')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Заявка на чемпионат',
                'verbose_name_plural': 'Заявки на чемпионаты',
                'unique_together': {('championship', 'team')},
            },
        ),
    ]
