# Generated by Django 6.0.5 on 2026-05-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_championshipteam_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='schedule_info',
            field=models.TextField(blank=True, verbose_name='Информация о сроках и месте проведения'),
        ),
    ]
